### ISSUE TITLE
dig dnsdocker.docker works, curl dnsdocker.docker doesn't

### ISSUE THREAD

**Issue by oliverwilkie** [tonistiigi/dnsdock#34] opened 2015-08-04 17:10 UTC
Hi

From one container I am able to ping another container but any attempt to do a higher-level request such as `curl` fails citing that it 'could not resolve host'. Any theories/suggestions why? Both containers are based off Ubuntu 14.04

```
root@ac69fc055883:/app# dig dnsdock.docker

; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> dnsdock.docker
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35804
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;dnsdock.docker.			IN	A

;; ANSWER SECTION:
dnsdock.docker.		0	IN	A	172.17.3.48

;; Query time: 1 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Tue Aug 04 17:16:58 UTC 2015
;; MSG SIZE  rcvd: 62

```
But when I curl...
```
root@fab381760c0e:/app# strace -o /tmp/wtf -fF curl -v http://dnsdock.docker/services
* Hostname was NOT found in DNS cache
* Could not resolve host: dnsdock.docker
* Closing connection 0
curl: (6) Could not resolve host: dnsdock.docker
```

**Comment by oliverwilkie** [comment] 2015-08-04 17:17
(accidentally posted wrong dig output, have corrected post)

**Comment by oliverwilkie** [comment] 2015-08-04 17:24
Note I *can* access http://dnsdock.docker/services from my host machine (Mac, Boot2Docker) having followed the README instructions of Mac OS X. I just can't get inter-container resolving to work.

**Comment by oliverwilkie** [comment] 2015-08-04 23:48
Update: `curl -4 -v http://dnsdock.docker/services` worked fine (IPv4)

**Comment by oliverwilkie** [comment] 2015-08-04 23:57
I think this is related to https://github.com/tonistiigi/dnsdock/issues/4

I was using tonistiigi/dnsdock:latest

If I instead use the latest available tagged build tonistiigi/dnsdock:v1.10.0 it works as expected

**Comment by bersace** [comment] 2015-08-31 12:05
Hi, We hit the same issue with base debian wheezy image.

Actually, the problem is that glibc resolver queries AAAA and A records. dnsdock sends NXDOMAIN for AAAA. This lead to failure, even if A is present. This is the implementation of glibc. curl -4 ignores AAAA, even if glibc resolv queries them.

dnsdock image 0dae40984f82 works fine. But latest (at the time of this comment) fails. The only solution we found was to downgrade to 0dae40984f82.

@tonistiigi can you reproduce this bug with a debian container ? Maybe busybox uses another resolver (eglibc ?) that handle properly NXDOMAIN in AAAA while A is ok.

**Comment by bersace** [comment] 2015-08-31 12:06
You can view this error with strace and tcpdump -i docker0 port 53

**Comment by bersace** [comment] 2015-08-31 12:06
cc @toopy

**Comment by mpeters** [comment] 2015-09-01 19:51
I'm also seeing this problem. It can easily be seen by using getent comparing the results of "hosts" vs "ahosts":

    $ getent hosts test.docker

    $ getent ahosts test.docker

"hosts" works, but "ahosts" doesn't. I can also confirm that dropping back to `v1.10.0` from `latest` fixes the issue.

**Comment by diogogmt** [comment] 2015-09-04 01:35
I'm facing similar issues with the latest build.

**In an ubuntu container:**

It works with:
* dig
* ping

Doesn't work with:
* curl
* wget
* nslookup

**On my mac**

It works with:
* ping
* dig
* curl

Doesn't work with:
* nslookup


If would help I could post some more detailed logs from the error scenarios.

**Comment by tonistiigi** [comment] 2015-09-04 01:40
@kgutwin do you know whats wrong here? do we need to revert #32 ?

**Comment by bersace** [comment] 2015-09-04 07:19
Hmm, looks like we get false NXDOMAIN. Maybe just a fix of #32 to actually get NOERROR.

Note that we override service name with DNSDOCK_ALIAS. Maybe #32 doesn't handle this case ?

**Comment by kgutwin** [comment] 2015-09-08 17:05
First - those of you still seeing NXDOMAIN on AAAA queries, can you verify you've pulled the latest `tonistiigi/dnsdock` image? I don't get NXDOMAIN from the image 3b38edc92eb7.

    root@244f9cf57b75:/# host -t AAAA dnsdock.docker
    dnsdock.docker has no AAAA record

However, I was able to reproduce the reported curl failure on Ubuntu 14.04.3. From the tcpdump output:

    16:59:11.997600 IP 172.18.0.3.50946 > 172.18.42.1.53: 16672+ A? dnsdock.docker. (32)
    16:59:11.997894 IP 172.18.0.3.50946 > 172.18.42.1.53: 44373+ AAAA? dnsdock.docker. (32)
    16:59:11.998397 IP 172.18.42.1.53 > 172.18.0.3.50946: 16672- 1/0/0 A 172.18.0.8 (62)
    16:59:11.998617 IP 172.18.42.1.53 > 172.18.0.3.50946: 44373- 0/1/0 (110)

Everything seemed to be ok, except the minus sign next to the query ID number on the replies. I traced that down to the lack of the 'recursion available' bit set on the reply packets. You can see that also as the "recursion requested but not available" warning from dig.

I'm not sure exactly why, but Ubuntu's resolver seems to care if recursion is requested but not available. Adding that bit to all replies seems to resolve the problem - see the PR below.

**Comment by kaluzki** [comment] 2015-09-13 20:56
with both pull requests from https://github.com/ps2/dnsdock curl works again

**Comment by diogogmt** [comment] 2015-09-15 12:10
Tested and verified that with the latest build from @ps2 most tools are now able to resolve the names.
Works with:
* ping
* dig
* curl
* wget

Still **nslookup** can't resolve domains, it keeps coming back as a name collision error as 127.0.53.53

I enabled some logs on dnsdock.
Below is the trace when I issue a ```nslookup helionode.cloud``` query

```
HandleRequest - dns:
;; opcode: QUERY, status: NOERROR, id: 27895
;; flags: rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;helionode.cloud.	IN	 A

---------
Setting reply
Cleaned query helionode.cloud
queryServices helionode.cloud
service &{helionode_test node-js-ubuntu 172.17.0.23 -1 [helionode.cloud]}
DNS Type 1
DNS TypeA, making service A - name helionode.cloud.
 service &{helionode_test node-js-ubuntu 172.17.0.23 -1 [helionode.cloud]}
makeServiceA - service &{helionode_test node-js-ubuntu 172.17.0.23 -1 [helionode.cloud]} - n helionode.cloud.
rr helionode.cloud.	0	IN	A	172.17.0.23
After making service A
Writting message ;; opcode: QUERY, status: NOERROR, id: 27895
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;helionode.cloud.	IN	 A

;; ANSWER SECTION:
helionode.cloud.	0	IN	A	172.17.0.23
+
```
﻿

**Comment by diogogmt** [comment] 2015-09-25 16:17
@tonistiigi any updates on this issue?
looks like the pr from https://github.com/ps2/dnsdock  solved the issue.

**Comment by diogogmt** [comment] 2015-10-04 23:13
Besides applying the patches from PRs #45 and #47 I also had to update the mikeg dns library to its latest version.

Now I can resolve the container DNS names using all tools. I tested both in a mac an ubuntu environment.

**Comment by WiR3D-kNiGhT** [comment] 2015-12-18 08:24
Its December already and published fixes for this haven't been merged into the repo? I don't mean to sound ungrateful, but if you aren't going to maintain this then at least let someone else, or say so.

I mean, I just wasted a day chasing what was wrong with this. Only to find this thread.

**Comment by nterray** [comment] 2016-01-28 10:15
I have the same issue. What is missing in order to merge PRs and fix it?

**Comment by eliasson86** [comment] 2016-01-28 15:56
Me too would like to see a merge happen here.

**Comment by ps2** [comment] 2016-02-13 03:12
Merged

**Closed by ps2** 2016-02-13 03:12 UTC
