### ISSUE TITLE
nginx errors when resolving

### ISSUE THREAD

**Issue by steffenmllr** [tonistiigi/dnsdock#4] opened 2014-10-17 08:48 UTC
Hey there - it's me again :)

Having some weird issue with nginx (nginx/1.7.5) . My error log is full of:

```
2014/10/17 10:42:21 [error] 25000#0: unexpected RR type 6
2014/10/17 10:42:21 [error] 25000#0: no A or CNAME types in DNS response
```

My nginx config uses:

````
    resolver 172.17.42.1 valid=1s;
    resolver_timeout 5s;
```

Also if recreate and start my docker container couple of times the nginx resolver does not find the container IP. After restarting the dnsdock container and nginx it works again.

Did you ran into similar problems ?

**Comment by Vad1mo** [comment] 2015-01-26 08:00
@steffenmllr did you find a solution? I am also stuck at the same spot now #7

**Comment by steffenmllr** [comment] 2015-01-26 09:01
I didn't run into the issue again but i also restart my nginx from time to time (it's only a testing server) - does it resolve if you restart nginx or are you hitting another error?

**Comment by steffenmllr** [comment] 2015-07-10 11:32
I just pulled the newest version and couldn't get it to run with `nginx 1.7.7`
If I set the resolver it logs an `Unimplemented` Error.

`2015/07/10 13:21:55 [error] 372#0: *1 app.docker could not be resolved (4: Unimplemented),`

It still shows those errors in `v1.5.0` with `nginx 1.7.7`
```
2015/07/10 13:29:19 [error] 1025#0: unexpected RR type 6
2015/07/10 13:29:19 [error] 1025#0: no A or CNAME types in DNS response
```

**Comment by wololock** [comment] 2015-07-16 10:40
I can confirm that, I also have the similar issue after pulling the latest image. It's very weird, because `nginx` and my java microservices have problem with resolving host names, while in the same time I can ping the hostname correctly from the container. For example `nginx` has a problem with resolving hostname like `user-management-service.docker`, but I can successfully do:

    docker exec -it te_nginx_1 sh
    ping user-management-service.docker

In that case `ping` reaches the given hostname.

I will try to downgrade to the previous image tag. One question: is it possible to get 1.9 or 1.10 image? In docker registry I can find only 1.6.0 as the most recent one. Thanks in advance!

**Comment by kgutwin** [comment] 2015-07-16 15:49
Can you post the output of `dig user-management-service.docker`?

**Comment by Groggy** [comment] 2015-07-22 06:52
I have the same issue with nginx v1.8.0. It works with dnsdock v1.8.0 but with latest, v1.10.0 and v1.9.0 I get this error :

```
2015/07/22 08:35:45 [error] 1502#0: *3 app.docker could not be resolved (4: Unimplemented), client: 127.0.0.1, server: ~^(?<application>\w+)\.docker$, request: "GET / HTTP/1.1", host: "app.docker"
```

**Comment by tonistiigi** [comment] 2015-07-22 07:04
@kgutwin probably a regression from #21 then

I believe nginx sends AAAA request first but not sure what kind of response it expects to carry on. Have to test.

**Comment by Vad1mo** [comment] 2015-07-22 07:09
we have rolled back to dnsdock 1.5, because for the same issue.

**Comment by kgutwin** [comment] 2015-07-22 12:10
Hi @Vad1mo, could you post the tcpdump output that you provided in #7 when using the latest dnsdock?

**Comment by Groggy** [comment] 2015-07-22 17:55
@tonistiigi you're right. If I disable IPv6, it works with latest dnsdock.

The working nginx configuration that I use is :
```
resolver 172.17.42.1 valid=1s ipv6=off;                                                                                                                                                                                          
resolver_timeout 5s;
```

**Comment by tonistiigi** [comment] 2015-07-22 19:26
@Groggy Cool. I didn't know this was configurable.

But we should have it working with default settings as well of course.

**Comment by kgutwin** [comment] 2015-07-22 19:49
I've found [RFC 4074](https://www.ietf.org/rfc/rfc4074.txt) that demonstrates the proper behavior for DNS servers when given an AAAA request. I'm now trying to sort out the best way to implement this RFC...

**Comment by mukulmajmudar** [comment] 2015-07-22 22:53
@Groggy thanks for the temporary workaround!

**Comment by tonistiigi** [comment] 2015-07-23 20:05
Can you guys test again with @kgutwin latest patches? Sadly I was still not able to reproduce this with current version.

**Comment by Groggy** [comment] 2015-07-24 18:48
@tonistiigi The latest version works for me even if I reactivate IPv6 DNS lookup. Nice work.

**Comment by tonistiigi** [comment] 2015-07-24 18:50
@Groggy Nice work indeed. All props to @kgutwin 

So I'm going to close this as fixed but feel free to post if this is still an issue for someone.

**Closed by tonistiigi** 2015-07-24 18:50 UTC

**Comment by jlopezr** [comment] 2015-08-04 19:43
Are the latest changes already in the docker hub container? I am having problems with nginx, but also with curl.

Start dnsdock:
```
vagrant@vagrant:~/Docker$ docker run -d -v /var/run/docker.sock:/var/run/docker.sock --name dnsdock -p 172.17.42.1:53:53/udp tonistiigi/dnsdock
52f9fda09c62c7f833435085553550e3a59882b703782d1ac37029f9f81a4a13
```
Dig shows that it is working perfectly:
```
vagrant@vagrant:~/Docker$ dig @172.17.42.1 dnsdock.docker

; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> @172.17.42.1 dnsdock.docker
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3925
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;dnsdock.docker.			IN	A

;; ANSWER SECTION:
dnsdock.docker.		0	IN	A	172.17.0.1

;; Query time: 1 msec
;; SERVER: 172.17.42.1#53(172.17.42.1)
;; WHEN: Tue Aug 04 20:30:06 UTC 2015
;; MSG SIZE  rcvd: 62
```
I change the host resolver configuration for a simple test, ping is working.
```
vagrant@vagrant:~/Docker$ cat /etc/resolv.conf
nameserver 172.17.42.1
search docker

vagrant@vagrant:~/Docker$ ping dnsdock
PING dnsdock.docker (172.17.0.1) 56(84) bytes of data.
64 bytes from dnsdock.docker (172.17.0.1): icmp_seq=1 ttl=64 time=0.037 ms
64 bytes from dnsdock.docker (172.17.0.1): icmp_seq=2 ttl=64 time=0.041 ms
64 bytes from dnsdock.docker (172.17.0.1): icmp_seq=3 ttl=64 time=0.041 ms
```
But if I try to use curl to list the services, it does not work: 
```
vagrant@vagrant:~/Docker$ curl http://dnsdock.docker/services
curl: (6) Could not resolve host: dnsdock.docker
```
Forcing curl to use ipv4 DNS resolution makes it work.
```
vagrant@vagrant:~/Docker$ curl -4 http://dnsdock.docker/services
{"52f9fda09c62c7f833435085553550e3a59882b703782d1ac37029f9f81a4a13":{"Name":"dnsdock","Image":"dnsdock","Ip":"172.17.0.1","Ttl":-1,"Aliases":[]}}
```

**Comment by katzefudder** [comment] 2015-08-24 10:18
I can still confirm this issue to the actual latest from hub.docker.com
The github tags for 1.11 and 1.12 are still missing on docker hub, as far as I can see atm.

**Comment by diogogmt** [comment] 2015-09-04 00:45
I'm building from HEAD and still hitting the same problem.

**Comment by ps2** [comment] 2015-09-11 18:37
same here; I can verify that I'm running with the latest fixes made by @kgutwin, and I still see issues the with curl (and ruby dns lookups as well).  Adding the -4 flag resolves the issue for curl, but I don't have such a simple fix on the ruby side.
